import React,{useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{Briefcase,CalendarDays,Dumbbell,Home,Settings,Shield,Wallet,BookOpen,ClipboardList}from"lucide-react";
import"./index.css";import{seedState}from"./data/seed";import{AppState}from"./types";
const key="dawson-os-v1";const load=():AppState=>{const s=localStorage.getItem(key);return s?JSON.parse(s):seedState};
const nav=[["Dashboard",ClipboardList],["Daily Mission",CalendarDays],["Career Command",Briefcase],["Federal LE",Shield],["Financial Independence",Wallet],["Fitness Readiness",Dumbbell],["Reading Intelligence",BookOpen],["Home Command",Home],["Settings",Settings]] as const;
function Progress({value}:{value:number}){return <div className="h-2 rounded-full bg-white/10"><div className="h-2 rounded-full bg-gold" style={{width:`${Math.min(100,Math.max(0,value))}%`}}/></div>}
function App(){const[page,setPage]=useState("Dashboard");const[state,setState]=useState<AppState>(load());const update=(n:AppState)=>{setState(n);localStorage.setItem(key,JSON.stringify(n))};const score=useMemo(()=>Math.round(state.checklist.filter(t=>t.done).length/state.checklist.length*100),[state.checklist]);
return <div className="min-h-screen bg-[radial-gradient(circle_at_top_left,#253858_0,#111D2E_35%,#0e141f_100%)]"><div className="flex">
<aside className="min-h-screen w-72 border-r border-white/10 bg-black/20 p-6"><div className="mb-8"><div className="label">DawsonOS</div><h1 className="mt-2 text-2xl font-bold">Command Center</h1><p className="mt-2 text-sm text-ivory/60">Courage • Integrity • Discipline</p></div><nav className="space-y-2">{nav.map(([item,Icon])=><button key={item} onClick={()=>setPage(item)} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm ${page===item?"bg-gold text-charcoal font-semibold":"text-ivory/80 hover:bg-white/10"}`}><Icon size={18}/>{item}</button>)}</nav></aside>
<main className="flex-1 p-8"><header className="mb-8 flex items-end justify-between"><div><div className="label">Personal Operating System</div><h2 className="mt-2 text-4xl font-bold">{page}</h2></div><div className="rounded-full border border-gold/40 px-4 py-2 text-sm text-gold">Mission Status: ACTIVE</div></header>
{page==="Dashboard"&&<div className="grid grid-cols-3 gap-5"><div className="card col-span-2"><div className="label">Mission</div><h3 className="mt-2 text-2xl font-semibold">Become financially stable, physically ready, and prepared for federal law enforcement.</h3><p className="mt-3 text-ivory/70">Lead by example. Listen first. Earn trust through consistent action.</p></div><div className="card"><div className="label">Daily Discipline</div><div className="mt-3 text-4xl font-bold">{score}%</div><Progress value={score}/></div><div className="card"><div className="label">Emergency Fund</div><div className="mt-3 text-3xl font-bold">${state.finance.emergencyFund}/$1,000</div><Progress value={state.finance.emergencyFund/10}/></div><div className="card"><div className="label">Current Weight</div><div className="mt-3 text-3xl font-bold">{state.weight} lb</div><p className="text-sm text-ivory/60">Goal: 230 lb</p></div><div className="card"><div className="label">Career Applications</div><div className="mt-3 text-3xl font-bold">{state.applications.length}</div><p className="text-sm text-ivory/60">Tracked applications</p></div><div className="card col-span-3"><div className="label">Top Three Priorities</div><div className="mt-4 grid grid-cols-3 gap-4">{state.topPriorities.map((p,i)=><div key={i} className="rounded-xl border border-white/10 bg-black/20 p-4">{p}</div>)}</div></div></div>}
{page==="Daily Mission"&&<div className="grid grid-cols-2 gap-5"><div className="card"><div className="label">Execution Checklist</div><div className="mt-4 space-y-3">{state.checklist.map(task=><label key={task.id} className="flex items-center gap-3 rounded-lg bg-black/20 p-3"><input type="checkbox" checked={task.done} onChange={()=>update({...state,checklist:state.checklist.map(t=>t.id===task.id?{...t,done:!t.done}:t)})}/><span className={task.done?"line-through text-ivory/50":""}>{task.text}</span></label>)}</div></div><div className="card"><div className="label">SITREP</div>{(["status","win","obstacle","correction","lesson","tomorrow"] as const).map(k=><div key={k} className="mt-3"><label className="mb-1 block text-sm capitalize text-ivory/70">{k}</label><textarea className="input min-h-[54px]" value={state.sitrep[k]} onChange={e=>update({...state,sitrep:{...state.sitrep,[k]:e.target.value}})}/></div>)}</div></div>}
{page==="Career Command"&&<Simple title="Application Tracker" items={state.applications.map(a=>`${a.company} — ${a.role} — ${a.status} — Follow up: ${a.followUp}`)}/>}
{page==="Federal LE"&&<Simple title="Federal Law Enforcement Readiness" items={["Research FBI, DEA, HSI, ATF, Secret Service, and U.S. Marshals","Organize background information","Track fitness standards","Prepare application documents","Build federal resume"]}/>}
{page==="Financial Independence"&&<Finance state={state} update={update}/>}
{page==="Fitness Readiness"&&<Simple title="Fitness Readiness" items={["Morning workout","Cardio and walking","Mobility","Weight tracking","Federal fitness test preparation"]}/>}
{page==="Reading Intelligence"&&<Simple title="Reading Intelligence" items={state.books.map(b=>`${b.title} — ${b.author} (${b.progress})`)}/>}
{page==="Home Command"&&<Simple title="Home Command" items={["Build executive-style apartment","White columns / presidential inspiration","Wood desk and leather chairs","Library and bookshelves","Intentional purchases only"]}/>}
{page==="Settings"&&<Simple title="System Settings" items={["Local-first storage","No cloud sync yet","Export/import next","Calendar/Gmail integration planned"]}/>}
</main></div></div>}
function Simple({title,items}:{title:string;items:string[]}){return <div className="card"><div className="label">{title}</div><div className="mt-4 grid gap-3">{items.map((x,i)=><div key={i} className="rounded-xl bg-black/20 p-4">{x}</div>)}</div></div>}
function Finance({state,update}:{state:AppState;update:(s:AppState)=>void}){return <div className="grid grid-cols-2 gap-5"><div className="card"><div className="label">Monthly Obligations</div><div className="mt-4 space-y-3"><div>Rent: $1,250 due on the 1st</div><div>Car loan: $307 due around the 15th</div><div>Electric/Gas: near end of month</div><div>Apple storage: ~$3/month</div><div>Xbox Game Pass: monthly</div></div></div><div className="card"><div className="label">Financial Independence</div><label className="mt-4 block text-sm text-ivory/70">Emergency Fund</label><input className="input mt-1" type="number" value={state.finance.emergencyFund} onChange={e=>update({...state,finance:{...state.finance,emergencyFund:Number(e.target.value)}})}/><div className="mt-4"><Progress value={state.finance.emergencyFund/10}/></div></div></div>}
createRoot(document.getElementById("root")!).render(<App/>);
